import type { Metadata } from "next";
import { Gilda_Display } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Holding from "./components/ui/holding";

const gildaDisplay = Gilda_Display({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark">
      <body className={gildaDisplay.className}>
        <div className="relative w-full flex items-center justify-center">
          <Navbar />
        </div>
        <Holding />
        {children}
      </body>
    </html>
  );
}